name = "server"
version = "1.0.0"
gleam = ">= 1.1.0"

[dependencies]
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
mist = ">= 2.0.0 and < 3.0.0"
wisp = ">= 1.1.0 and < 2.0.0"
mungo = ">= 0.26.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
